name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: demo_credit_db
      DB_PORT: 3306
      ADJUTOR_API_KEY: test-key
      NODE_ENV: test
      PORT: 3300
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      # - name: Copy .env.example to .env
      #   run: cp .env.example .env
      - run: pnpm test
